export const API_URL = 'https://app.admss.com/api/v1/';
export const LOC_STORAGE_USER = 'admss-admin-user';
export const LOC_STORAGE_USER_STATE = 'admss-user-current-state';
export const APPLICATION = 'admin';

export const renamedKeys: Record<string, string> = {
    dealType: 'Deal Type',
    dealStatus: 'Deal Status',
    feeDefDocumentation: 'Documentation Fee',
    feeDefvehiclePack: 'Vehicle Pack Fee',
    feeDefTitle: 'Title Fee',
    feeDefTag: 'Tag Fee',
    feeDefTransfer: 'Transfer Fee',
    feeDefSpareTag: 'Spare Tag Fee',
    feeDefSpareTransferTag: 'Spare Transfer Tag Fee',
    taxDefStateVehicleTaxRate: 'State Vehicle Tax Rate',
    stocknumSequental: 'Stock Number is Sequential',
    stocknumPrefix: 'Stock Number Prefix',
    stocknumSuffix: 'Stock Number Suffix',
    stocknumLast6ofVIN: 'Stock Number Last 6 of VIN Symbols',
    stocknumLast8ofVIN: 'Stock Number Last 8 of VIN Symbols',
    stocknumFixedDigits: 'Stock Number Fixed Digits',
    stocknumtiSequental: 'Stock Number Is Sequential',
    stocknumtiPrefix: 'Stock Number Prefix',
    stocknumtiSuffix: 'Stock Number Suffix',
    stocknumtiLast6ofVIN: 'Stock Number Last 6 of VIN Symbols',
    stocknumtiLast8ofVIN: 'Stock Number Last 8 of VIN Symbols',
    stocknumtiFixedDigits: 'Stock Number Fixed Digits',
    stocknumtiFromSoldVehicle: 'Stock Number From Sold Vehicle',
    accountStartNumber: 'Account Start Number',
    accountFixedDigits: 'Account Fixed Digits',
    accountPrefix: 'Account Prefix',
    accountSuffix: 'Account Suffix',
    accountLateFeeMin: 'Account Late Fee Min',
    accountLateFeeMax: 'Account Late Fee Max',
    accountLateFeePercentage: 'Account Late Fee Percentage',
    accountLateFeeGracePeriod: 'Account Late Fee Grace Period',
    contractDefInterestRate: 'Contract Default Interest Rate',
    contractPaymentFrequency: 'Contract Payment Frequency',
    leaseMoneyFactor: 'Lease Money Factor',
    leaseDefaultMileage: 'Lease Default Mileage',
    leaseOverageAmount: 'Lease Overage Amount',
    leaseTerm: 'Lease Term',
    leasePaymentFrequency: 'Lease Payment Frequency',
    created: 'Created Date',
    index: 'Index',
    itemuid: 'Item UID',
    isdefault: 'Is Default',
    updated: 'Updated Date',
    useruid: 'User UID',
    locEmail1: 'Location Email 1',
    locEmail2: 'Location Email 2',
    locManager1: 'Location Manager 1',
    locManager2: 'Location Manager 2',
    locName: 'Location Name',
    locPhone1: 'Location Phone 1',
    locPhone2: 'Location Phone 2',
    locState: 'Location State',
    locStreetAddress: 'Location Street Address',
    locWeb: 'Location Website',
    locZIP: 'Location ZIP',
    locuid: 'Location UID',
    uaSystemAdmin: 'System Admin',
    uaManager: 'Manager',
    uaClientAdmin: 'Client Admin',
    uaLocationAdmin: 'Location Admin',
    uaSalesPerson: 'Salesperson',
    uaViewInventory: 'View Inventory',
    uaAddInventory: 'Add Inventory',
    uaEditInventory: 'Edit Inventory',
    uaViewCostsAndExpenses: 'View Costs And Expenses',
    uaAddExpenses: 'Add Expenses',
    uaEditExpenses: 'Edit Expenses',
    uaDeleteInventory: 'Delete Inventory',
    uaViewContacts: 'View Contacts',
    uaAddContacts: 'Add Contacts',
    uaEditContacts: 'Edit Contacts',
    uaDeleteContacts: 'Delete Contacts',
    uaViewDeals: 'View Deals',
    uaAddDeals: 'Add Deals',
    uaEditDeals: 'Edit Deals',
    uaEditInsuranceOnly: 'Edit Insurance Only',
    uaPrintDealsForms: 'Print Deals Forms',
    uaEditDealWashout: 'Edit Deal Washout',
    uaEditPaidComissions: 'Edit Paid Commissions',
    uaDeleteDeal: 'Delete Deal',
    uaViewAccounts: 'View Accounts',
    uaEditPayments: 'Edit Payments',
    uaDeletePayments: 'Delete Payments',
    uaAddCreditsAndFees: 'Add Credits And Fees',
    uaDeleteAccounts: 'Delete Accounts',
    uaChangePayments: 'Change Payments',
    uaAllowBackDatingPayments: 'Allow Back Dating Payments',
    uaAllowPartialPayments: 'Allow Partial Payments',
    uaCreateUsers: 'Create Users',
    uaEditSettings: 'Edit Settings',
    uaAllowPaymentCalculator: 'Allow Payment Calculator',
    uaAllowPaymentQuote: 'Allow Payment Quote',
    uaAllowReports: 'Allow Reports',
    uaAllowPrinting: 'Allow Printing',
    uaAllowMobile: 'Allow Mobile',
    uaAllowWeb: 'Allow Web',
};
